### ISSUE TITLE
latest tag points to older LTS release

### ISSUE THREAD

**Issue by serverhorror** [tozd/docker-meteor#7]
(Thank you so much for this great piece! Keep up the work, I've gone from "*no meteor ever*" to "*full production deployment*" in less than 2 days now -- THANKS!)

The

* `...:latest` points to `...:ubuntu-trusty`

I think this should really go to `...:ubuntu-xenial` as this is quite confusing for users of the image

**Comment by mitar** [comment]
`latest` is here only for backwards compatibility. You should not use it. You should always select the LTS you want to use, and then you should switch to a new version when you are ready. Whole concept of `latest` tag is buggy. If I change it, anyone using it will have things broken because the base image would change under them without them noticing. I would just remove it, but then again it might break existing things.

So, sadly, I do not see a way forward here. But I do not think it is the right thing to change it now. It should not even exist to begin with.
